import Footer from "@/Components/Footer/Footer";
import Header from "@/Components/Header/Header";
import { QuickSandFont } from "@/Utils/Fonts";
import "@/styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={QuickSandFont.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
